import Header from "@/component/header/Header.jsx";
import "./globals.css";
import Footer from "@/component/footer/Footer.jsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body className="bgColor">
        {children}
        <Footer />
        <Header />
      </body>
    </html>
  );
}
